//! Access control profiles updated for DL36.
//!
//! The existing `idm_acp_connector_admin` ACP gains the three new DL36
//! Bitbucket Cloud connector attributes in its search / modify / create allowlists.
//!
//! Forked from `IDM_ACP_OAUTH2_CLIENT_ADMIN_DL35`; unchanged except for
//! the new attribute additions.

use crate::constants::{
    UUID_IDM_ACP_OAUTH2_CLIENT_ADMIN, UUID_IDM_OAUTH2_CLIENT_ADMINS, UUID_SYSTEM_ADMINS,
};
use crate::prelude::*;

pub(crate) use crate::migration_data::dl21::access::{
    BuiltinAcp, BuiltinAcpReceiver, BuiltinAcpTarget,
};

static FILTER_RECYCLED_OR_TOMBSTONE_DL36: LazyLock<ProtoFilter> = LazyLock::new(|| {
    ProtoFilter::Or(vec![
        match_class_filter!(EntryClass::Recycled),
        match_class_filter!(EntryClass::Tombstone),
    ])
});

static FILTER_ANDNOT_TOMBSTONE_OR_RECYCLED_DL36: LazyLock<ProtoFilter> =
    LazyLock::new(|| ProtoFilter::AndNot(Box::new(FILTER_RECYCLED_OR_TOMBSTONE_DL36.clone())));

/// DL36 refresh of `idm_acp_connector_admin`. Forks DL35 and adds the
/// three Bitbucket Cloud connector config attributes introduced by PR-CONNECTOR-BITBUCKET.
pub(crate) static IDM_ACP_OAUTH2_CLIENT_ADMIN_DL36: LazyLock<BuiltinAcp> =
    LazyLock::new(|| BuiltinAcp {
        classes: vec![
            EntryClass::Object,
            EntryClass::AccessControlCreate,
            EntryClass::AccessControlModify,
            EntryClass::AccessControlProfile,
            EntryClass::AccessControlSearch,
        ],
        name: "idm_acp_connector_admin",
        uuid: UUID_IDM_ACP_OAUTH2_CLIENT_ADMIN,
        description:
            "Builtin IDM Control for granting oauth2 trust provider administration rights.",
        receiver: BuiltinAcpReceiver::Group(vec![
            UUID_IDM_OAUTH2_CLIENT_ADMINS,
            UUID_SYSTEM_ADMINS,
        ]),
        target: BuiltinAcpTarget::Filter(ProtoFilter::And(vec![
            match_class_filter!(EntryClass::Connector),
            FILTER_ANDNOT_TOMBSTONE_OR_RECYCLED_DL36.clone(),
        ])),
        search_attrs: vec![
            Attribute::Class,
            Attribute::Uuid,
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::Spn,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28 additions
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29 additions
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30 additions
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31 additions
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32 additions
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34 additions
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35 additions
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36 additions
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
        ],
        modify_present_attrs: vec![
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28 additions
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29 additions
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30 additions
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31 additions
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32 additions
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34 additions
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35 additions
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36 additions
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
        ],
        modify_removed_attrs: vec![
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28 additions
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29 additions
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30 additions
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31 additions
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32 additions
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34 additions
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35 additions
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36 additions
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
        ],
        create_attrs: vec![
            Attribute::Class,
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28 additions
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29 additions
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30 additions
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31 additions
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32 additions
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34 additions
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35 additions
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36 additions
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
        ],
        create_classes: vec![EntryClass::Object, EntryClass::Connector],
        ..Default::default()
    });
