//! Access control profiles updated for DL37.
//!
//! Three ACPs are updated or added:
//! 1. `idm_acp_connector_admin` — adds `ConnectorGithubUseLoginAsId`.
//!    Forked from `IDM_ACP_OAUTH2_CLIENT_ADMIN_DL36`.
//! 2. `idm_acp_oauth2_manage` — adds `Oauth2RsTrustedPeers` and
//!    `Oauth2RsAllowedConnectors`. Forked from `IDM_ACP_OAUTH2_MANAGE_DL26`.
//! 3. `idm_acp_provider_identity_manage` — new ACP for `ProviderIdentity` entries.
//!    Granted to system admins only.

use crate::constants::{
    UUID_IDM_ACP_OAUTH2_CLIENT_ADMIN, UUID_IDM_ACP_OAUTH2_MANAGE_V1,
    UUID_IDM_ACP_PROVIDER_IDENTITY_MANAGE, UUID_IDM_OAUTH2_ADMINS, UUID_IDM_OAUTH2_CLIENT_ADMINS,
    UUID_SYSTEM_ADMINS,
};
use crate::prelude::*;

pub(crate) use crate::migration_data::dl21::access::{
    BuiltinAcp, BuiltinAcpReceiver, BuiltinAcpTarget,
};

static FILTER_RECYCLED_OR_TOMBSTONE_DL37: LazyLock<ProtoFilter> = LazyLock::new(|| {
    ProtoFilter::Or(vec![
        match_class_filter!(EntryClass::Recycled),
        match_class_filter!(EntryClass::Tombstone),
    ])
});

static FILTER_ANDNOT_TOMBSTONE_OR_RECYCLED_DL37: LazyLock<ProtoFilter> =
    LazyLock::new(|| ProtoFilter::AndNot(Box::new(FILTER_RECYCLED_OR_TOMBSTONE_DL37.clone())));

// ─── Connector admin ACP (adds ConnectorGithubUseLoginAsId) ─────────────────

/// DL37 refresh of `idm_acp_connector_admin`. Forks DL36 and adds
/// `ConnectorGithubUseLoginAsId` to search/modify/create allowlists.
pub(crate) static IDM_ACP_OAUTH2_CLIENT_ADMIN_DL37: LazyLock<BuiltinAcp> =
    LazyLock::new(|| BuiltinAcp {
        classes: vec![
            EntryClass::Object,
            EntryClass::AccessControlCreate,
            EntryClass::AccessControlModify,
            EntryClass::AccessControlProfile,
            EntryClass::AccessControlSearch,
        ],
        name: "idm_acp_connector_admin",
        uuid: UUID_IDM_ACP_OAUTH2_CLIENT_ADMIN,
        description:
            "Builtin IDM Control for granting oauth2 trust provider administration rights.",
        receiver: BuiltinAcpReceiver::Group(vec![
            UUID_IDM_OAUTH2_CLIENT_ADMINS,
            UUID_SYSTEM_ADMINS,
        ]),
        target: BuiltinAcpTarget::Filter(ProtoFilter::And(vec![
            match_class_filter!(EntryClass::Connector),
            FILTER_ANDNOT_TOMBSTONE_OR_RECYCLED_DL37.clone(),
        ])),
        search_attrs: vec![
            Attribute::Class,
            Attribute::Uuid,
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::Spn,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
            // DL37
            Attribute::ConnectorGithubUseLoginAsId,
        ],
        modify_present_attrs: vec![
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
            // DL37
            Attribute::ConnectorGithubUseLoginAsId,
        ],
        modify_removed_attrs: vec![
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
            // DL37
            Attribute::ConnectorGithubUseLoginAsId,
        ],
        create_attrs: vec![
            Attribute::Class,
            Attribute::Name,
            Attribute::DisplayName,
            Attribute::ConnectorId,
            Attribute::ConnectorSecret,
            Attribute::OAuth2AuthorisationEndpoint,
            Attribute::OAuth2TokenEndpoint,
            Attribute::OAuth2UserinfoEndpoint,
            Attribute::OAuth2RequestScopes,
            Attribute::OAuth2JitProvisioning,
            Attribute::OAuth2EmailLinkAccounts,
            Attribute::ConnectorLogoUri,
            Attribute::OAuth2Issuer,
            Attribute::OAuth2JwksUri,
            Attribute::OAuth2LinkBy,
            Attribute::OAuth2GroupMapping,
            // DL28
            Attribute::ConnectorProviderKind,
            Attribute::ConnectorGithubHost,
            Attribute::ConnectorGithubOrgFilter,
            Attribute::ConnectorGithubAllowedTeams,
            Attribute::ConnectorGithubTeamNameField,
            Attribute::ConnectorGithubLoadAllGroups,
            Attribute::ConnectorGithubPreferredEmailDomain,
            Attribute::ConnectorGithubAllowJitProvisioning,
            // DL29
            Attribute::ConnectorOidcEnableGroups,
            Attribute::ConnectorOidcGroupsKey,
            Attribute::ConnectorOidcSkipEmailVerified,
            Attribute::ConnectorOidcAllowedGroups,
            Attribute::ConnectorOidcGetUserInfo,
            Attribute::ConnectorOidcUserIdKey,
            Attribute::ConnectorOidcUserNameKey,
            Attribute::ConnectorOidcOverrideClaimMapping,
            Attribute::ConnectorOidcGroupsPrefix,
            Attribute::ConnectorOidcGroupsSuffix,
            // DL30
            Attribute::ConnectorGoogleHostedDomain,
            Attribute::ConnectorGoogleServiceAccountJson,
            Attribute::ConnectorGoogleAdminEmail,
            Attribute::ConnectorGoogleFetchGroups,
            // DL31
            Attribute::ConnectorMicrosoftTenant,
            Attribute::ConnectorMicrosoftOnlySecurityGroups,
            Attribute::ConnectorMicrosoftGroups,
            Attribute::ConnectorMicrosoftGroupNameFormat,
            Attribute::ConnectorMicrosoftUseGroupsAsWhitelist,
            Attribute::ConnectorMicrosoftEmailToLowercase,
            Attribute::ConnectorMicrosoftApiUrl,
            Attribute::ConnectorMicrosoftGraphUrl,
            Attribute::ConnectorMicrosoftPromptType,
            Attribute::ConnectorMicrosoftDomainHint,
            Attribute::ConnectorMicrosoftScopes,
            Attribute::ConnectorMicrosoftPreferredUsernameField,
            Attribute::ConnectorMicrosoftAllowJitProvisioning,
            // DL32
            Attribute::ConnectorLdapHost,
            Attribute::ConnectorLdapInsecureNoSsl,
            Attribute::ConnectorLdapInsecureSkipVerify,
            Attribute::ConnectorLdapStartTls,
            Attribute::ConnectorLdapRootCaData,
            Attribute::ConnectorLdapClientCert,
            Attribute::ConnectorLdapClientKey,
            Attribute::ConnectorLdapBindDn,
            Attribute::ConnectorLdapBindPw,
            Attribute::ConnectorLdapUsernamePrompt,
            Attribute::ConnectorLdapUserSearchBaseDn,
            Attribute::ConnectorLdapUserSearchFilter,
            Attribute::ConnectorLdapUserSearchUsername,
            Attribute::ConnectorLdapUserSearchScope,
            Attribute::ConnectorLdapUserSearchIdAttr,
            Attribute::ConnectorLdapUserSearchEmailAttr,
            Attribute::ConnectorLdapUserSearchNameAttr,
            Attribute::ConnectorLdapUserSearchPreferredUsernameAttr,
            Attribute::ConnectorLdapUserSearchEmailSuffix,
            Attribute::ConnectorLdapGroupSearchBaseDn,
            Attribute::ConnectorLdapGroupSearchFilter,
            Attribute::ConnectorLdapGroupSearchScope,
            Attribute::ConnectorLdapGroupSearchUserMatchers,
            Attribute::ConnectorLdapGroupSearchNameAttr,
            // DL34
            Attribute::ConnectorOpenshiftIssuer,
            Attribute::ConnectorOpenshiftGroups,
            Attribute::ConnectorOpenshiftInsecureCa,
            Attribute::ConnectorOpenshiftRootCa,
            // DL35
            Attribute::ConnectorGitlabBaseUrl,
            Attribute::ConnectorGitlabGroups,
            Attribute::ConnectorGitlabUseLoginAsId,
            Attribute::ConnectorGitlabGetGroupsPermission,
            Attribute::ConnectorGitlabRootCa,
            // DL36
            Attribute::ConnectorBitbucketTeams,
            Attribute::ConnectorBitbucketGetWorkspacePermissions,
            Attribute::ConnectorBitbucketIncludeTeamGroups,
            // DL37
            Attribute::ConnectorGithubUseLoginAsId,
        ],
        create_classes: vec![EntryClass::Object, EntryClass::Connector],
        ..Default::default()
    });

// ─── OAuth2 manage ACP (adds Oauth2RsTrustedPeers + Oauth2RsAllowedConnectors) ─

/// DL37 refresh of `idm_acp_oauth2_manage`. Forks DL26 and adds the two new
/// `OAuth2ResourceServer` attrs from DL37 to all allowlists.
pub(crate) static IDM_ACP_OAUTH2_MANAGE_DL37: LazyLock<BuiltinAcp> = LazyLock::new(|| BuiltinAcp {
    classes: vec![
        EntryClass::Object,
        EntryClass::AccessControlProfile,
        EntryClass::AccessControlCreate,
        EntryClass::AccessControlDelete,
        EntryClass::AccessControlModify,
        EntryClass::AccessControlSearch,
    ],
    name: "idm_acp_oauth2_manage",
    uuid: UUID_IDM_ACP_OAUTH2_MANAGE_V1,
    description: "Builtin IDM Control for managing OAuth2 resource server integrations.",
    receiver: BuiltinAcpReceiver::Group(vec![UUID_IDM_OAUTH2_ADMINS]),
    target: BuiltinAcpTarget::Filter(ProtoFilter::And(vec![
        match_class_filter!(EntryClass::OAuth2ResourceServer),
        FILTER_ANDNOT_TOMBSTONE_OR_RECYCLED_DL37.clone(),
    ])),
    search_attrs: vec![
        Attribute::Class,
        Attribute::Description,
        Attribute::DisplayName,
        Attribute::Name,
        Attribute::Uuid,
        Attribute::Spn,
        Attribute::OAuth2Session,
        Attribute::OAuth2RsOrigin,
        Attribute::OAuth2RsOriginLanding,
        Attribute::OAuth2RsScopeMap,
        Attribute::OAuth2RsSupScopeMap,
        Attribute::OAuth2RsBasicSecret,
        Attribute::OAuth2AllowInsecureClientDisablePkce,
        Attribute::OAuth2JwtLegacyCryptoEnable,
        Attribute::OAuth2PreferShortUsername,
        Attribute::OAuth2AllowLocalhostRedirect,
        Attribute::OAuth2RsClaimMap,
        Attribute::Image,
        Attribute::OAuth2StrictRedirectUri,
        Attribute::OAuth2DeviceFlowEnable,
        Attribute::KeyInternalData,
        // DL26
        Attribute::OAuth2RsPostLogoutRedirectUri,
        Attribute::OAuth2RsBackchannelLogoutUri,
        // DL37
        Attribute::Oauth2RsTrustedPeers,
        Attribute::Oauth2RsAllowedConnectors,
    ],
    modify_removed_attrs: vec![
        Attribute::Description,
        Attribute::DisplayName,
        Attribute::Name,
        Attribute::OAuth2Session,
        Attribute::OAuth2RsOrigin,
        Attribute::OAuth2RsOriginLanding,
        Attribute::OAuth2RsScopeMap,
        Attribute::OAuth2RsSupScopeMap,
        Attribute::OAuth2RsBasicSecret,
        Attribute::OAuth2AllowInsecureClientDisablePkce,
        Attribute::OAuth2JwtLegacyCryptoEnable,
        Attribute::OAuth2PreferShortUsername,
        Attribute::OAuth2AllowLocalhostRedirect,
        Attribute::OAuth2RsClaimMap,
        Attribute::Image,
        Attribute::OAuth2StrictRedirectUri,
        Attribute::OAuth2DeviceFlowEnable,
        Attribute::KeyActionRevoke,
        Attribute::KeyActionRotate,
        // DL26
        Attribute::OAuth2RsPostLogoutRedirectUri,
        Attribute::OAuth2RsBackchannelLogoutUri,
        // DL37
        Attribute::Oauth2RsTrustedPeers,
        Attribute::Oauth2RsAllowedConnectors,
    ],
    modify_present_attrs: vec![
        Attribute::Description,
        Attribute::DisplayName,
        Attribute::Name,
        Attribute::OAuth2RsOrigin,
        Attribute::OAuth2RsOriginLanding,
        Attribute::OAuth2RsSupScopeMap,
        Attribute::OAuth2RsScopeMap,
        Attribute::OAuth2AllowInsecureClientDisablePkce,
        Attribute::OAuth2JwtLegacyCryptoEnable,
        Attribute::OAuth2PreferShortUsername,
        Attribute::OAuth2AllowLocalhostRedirect,
        Attribute::OAuth2RsClaimMap,
        Attribute::Image,
        Attribute::OAuth2StrictRedirectUri,
        Attribute::OAuth2DeviceFlowEnable,
        Attribute::KeyActionRevoke,
        Attribute::KeyActionRotate,
        // DL26
        Attribute::OAuth2RsPostLogoutRedirectUri,
        Attribute::OAuth2RsBackchannelLogoutUri,
        // DL37
        Attribute::Oauth2RsTrustedPeers,
        Attribute::Oauth2RsAllowedConnectors,
    ],
    create_attrs: vec![
        Attribute::Class,
        Attribute::Description,
        Attribute::Name,
        Attribute::DisplayName,
        Attribute::OAuth2RsName,
        Attribute::OAuth2RsOrigin,
        Attribute::OAuth2RsOriginLanding,
        Attribute::OAuth2RsSupScopeMap,
        Attribute::OAuth2RsScopeMap,
        Attribute::OAuth2AllowInsecureClientDisablePkce,
        Attribute::OAuth2JwtLegacyCryptoEnable,
        Attribute::OAuth2PreferShortUsername,
        Attribute::OAuth2AllowLocalhostRedirect,
        Attribute::OAuth2RsClaimMap,
        Attribute::Image,
        Attribute::OAuth2StrictRedirectUri,
        Attribute::OAuth2DeviceFlowEnable,
        // DL26
        Attribute::OAuth2RsPostLogoutRedirectUri,
        Attribute::OAuth2RsBackchannelLogoutUri,
        // DL37
        Attribute::Oauth2RsTrustedPeers,
        Attribute::Oauth2RsAllowedConnectors,
    ],
    create_classes: vec![
        EntryClass::Object,
        EntryClass::Account,
        EntryClass::OAuth2ResourceServer,
        EntryClass::OAuth2ResourceServerBasic,
        EntryClass::OAuth2ResourceServerPublic,
    ],
    ..Default::default()
});

// ─── ProviderIdentity manage ACP ─────────────────────────────────────────────

/// New ACP for creating and managing `ProviderIdentity` entries.
/// Granted to system admins only — these records are written by the server during
/// federated login, not by end users.
pub(crate) static IDM_ACP_PROVIDER_IDENTITY_MANAGE_DL37: LazyLock<BuiltinAcp> =
    LazyLock::new(|| BuiltinAcp {
        classes: vec![
            EntryClass::Object,
            EntryClass::AccessControlCreate,
            EntryClass::AccessControlModify,
            EntryClass::AccessControlProfile,
            EntryClass::AccessControlSearch,
            EntryClass::AccessControlDelete,
        ],
        name: "idm_acp_provider_identity_manage",
        uuid: UUID_IDM_ACP_PROVIDER_IDENTITY_MANAGE,
        description: "Builtin IDM Control for managing provider identity records.",
        receiver: BuiltinAcpReceiver::Group(vec![UUID_SYSTEM_ADMINS]),
        target: BuiltinAcpTarget::Filter(ProtoFilter::And(vec![
            match_class_filter!(EntryClass::ProviderIdentity),
            FILTER_ANDNOT_TOMBSTONE_OR_RECYCLED_DL37.clone(),
        ])),
        search_attrs: vec![
            Attribute::Class,
            Attribute::Uuid,
            Attribute::Name,
            Attribute::ProviderIdentityUserUuid,
            Attribute::ProviderIdentityConnectorId,
            Attribute::ProviderIdentityClaimsUserId,
            Attribute::ProviderIdentityClaimsUsername,
            Attribute::ProviderIdentityClaimsEmail,
            Attribute::ProviderIdentityClaimsEmailVerified,
            Attribute::ProviderIdentityClaimsGroups,
            Attribute::ProviderIdentityConsents,
            Attribute::ProviderIdentityCreatedAt,
            Attribute::ProviderIdentityLastLogin,
            Attribute::ProviderIdentityBlockedUntil,
        ],
        modify_present_attrs: vec![
            Attribute::ProviderIdentityClaimsUserId,
            Attribute::ProviderIdentityClaimsUsername,
            Attribute::ProviderIdentityClaimsEmail,
            Attribute::ProviderIdentityClaimsEmailVerified,
            Attribute::ProviderIdentityClaimsGroups,
            Attribute::ProviderIdentityConsents,
            Attribute::ProviderIdentityCreatedAt,
            Attribute::ProviderIdentityLastLogin,
            Attribute::ProviderIdentityBlockedUntil,
        ],
        modify_removed_attrs: vec![
            Attribute::ProviderIdentityClaimsUserId,
            Attribute::ProviderIdentityClaimsUsername,
            Attribute::ProviderIdentityClaimsEmail,
            Attribute::ProviderIdentityClaimsEmailVerified,
            Attribute::ProviderIdentityClaimsGroups,
            Attribute::ProviderIdentityConsents,
            Attribute::ProviderIdentityCreatedAt,
            Attribute::ProviderIdentityLastLogin,
            Attribute::ProviderIdentityBlockedUntil,
        ],
        create_attrs: vec![
            Attribute::Class,
            Attribute::Name,
            Attribute::ProviderIdentityUserUuid,
            Attribute::ProviderIdentityConnectorId,
            Attribute::ProviderIdentityClaimsUserId,
            Attribute::ProviderIdentityClaimsUsername,
            Attribute::ProviderIdentityClaimsEmail,
            Attribute::ProviderIdentityClaimsEmailVerified,
            Attribute::ProviderIdentityClaimsGroups,
            Attribute::ProviderIdentityConsents,
            Attribute::ProviderIdentityCreatedAt,
            Attribute::ProviderIdentityLastLogin,
            Attribute::ProviderIdentityBlockedUntil,
        ],
        create_classes: vec![EntryClass::Object, EntryClass::ProviderIdentity],
        ..Default::default()
    });
